return {
	"lukas-reineke/indent-blankline.nvim",
	event = { "BufReadPost", "BufNewFile" },
	opts = {
		char = "▏",
		show_end_of_line = true,
		filetype_exclude = {
			"help",
			"packer",
			"dashboard",
			"alpha",
			"NvimTree",
			"man",
			"lspinfo",
			"TelescopePromt",
		},
		show_current_context = true,
		show_current_context_start = true,
		context_patterns = {
			"class",
			"function",
			"method",
			"^if",
			"^while",
			"^for",
			"^object",
			"^table",
			"block",
			"arguments",
		},
	},
	config = true,
}
